WithoutDbVerison/BaseApp.Web/Models/Api/TrustPay/CheckTrustPayPaymentInput.cs
using System.ComponentModel.DataAnnotations;

namespace AlphaPointPayment.Web.Models.Api.TrustPay
{
    public class CheckTrustPayPaymentInput
    {
        [Required]
        public string resourcePath { get; set; }
		
		[Required]
		public string checkoutId { get; set; }
    }
}

WithoutDbVerison/BaseApp.Web/Models/Api/TrustPay/CheckTrustPayPaymentOutput.cs
namespace AlphaPointPayment.Web.Models.Api.TrustPay
{
    public class CheckTrustPayPaymentOutput
    {
        public string Message { get; set; }
    }
}

WithoutDbVerison/BaseApp.Web/Models/Api/TrustPay/CreateNewPaymentInput.cs
using BaseApp.Common;
using System.ComponentModel.DataAnnotations;

namespace AlphaPointPayment.Web.Models.Api.TrustPay
{
    public class CreateNewPaymentInput
    {
        [Required]
        public string CheckoutId { get; set; }

        public Enums.Currencies Currency { get; set; }

        public decimal Amount { get; set; }

        public string UserAccountId { get; set; }
    }
}

WithoutDbVerison/BaseApp.Web/Models/Api/TrustPay/PrepareCheckoutInput.cs
using BaseApp.Common;

namespace AlphaPointPayment.Web.Models.Api.TrustPay
{
    public class PrepareCheckoutInput
    {
        public decimal Amount { get; set; }

        public Enums.Currencies Currency { get; set; }
    }
}

WithoutDbVerison/BaseApp.Web/Models/Api/TrustPay/PrepareCheckoutOutput.cs
using BaseApp.Common;

namespace AlphaPointPayment.Web.Models.Api.TrustPay
{
    public class PrepareCheckoutOutput
    {
        public PrepareCheckoutOutput(string checkoutId, string description)
        {
            CheckoutId = checkoutId;
            TrustPayDescription = description;
        }

        public string CheckoutId { get; set; }

        public string TrustPayCode { get; set; }

        public string TrustPayDescription { get; set; }

        public string ScriptSrc => $"{ConfigSettings.TrustPayBaseUrl}v1/paymentWidgets.js?checkoutId={CheckoutId}";

    }
}

WithoutDbVerison/BaseApp.Web/Models/Api/TrustPay/TrustPayPaymentDto.cs
using BaseApp.Common;
using System;

namespace AlphaPointPayment.Web.Models.Api.TrustPay
{
    public class TrustPayPaymentDto
    {
        public int Id { get; set; }

        public DateTime CreationTime { get; set; }

        public string CheckoutId { get; set; }

        public Enums.Currencies Currency { get; set; }

        public decimal Amount { get; set; }

        public string UserAccountId { get; set; }

        public Enums.PaymentStatuses PaymentStatus { get; set; }

        public DateTime? SubmittedTime { get; set; }
    }
}

WithoutDbVerison/BaseApp.Web/Models/TrustPay/PrePaymentInfoViewModel.cs
using BaseApp.Common;

namespace AlphaPointPayment.Web.Models.TrustPay
{
    public class PrePaymentInfoViewModel
    {
        public decimal Amount { get; set; }

        public Enums.Currencies Currency { get; set; }
    }
}

WithoutDbVerison/BaseApp.Web/Models/TrustPay/TrustPayRedirectInput.cs
namespace AlphaPointPayment.Web.Models.TrustPay
{
    public class TrustPayRedirectInput
    {
        public string id { get; set; }

        public string resourcePath { get; set; }        
    }
}

WithoutDbVerison/BaseApp.Web/Controllers/TrustPayController.cs
using AlphaPointPayment.Web.Models.TrustPay;
using BaseApp.Web.Code.Infrastructure.BaseControllers;
using System.Web.Mvc;

namespace AlphaPointPayment.Web.Controllers
{
    public class TrustPayController : ControllerBaseNoAuthorize
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetPrePaymentInfo(PrePaymentInfoViewModel model)
        {
            return PartialView("_PrePaymentInfo", model);
        }

        [HttpGet]
        public ActionResult TrustPayRedirect([System.Web.Http.FromUri] TrustPayRedirectInput input)
        {
            return View(input);
        }
    }
}

WithoutDbVerison/BaseApp.Web/Views/TrustPay/Index.cshtml
@using AlphaPointPayment.Web.Models.Api.TrustPay
@{
    ViewBag.Title = "Index";
}
<h4 style="text-align:center">
    Pay with TrustPay
</h4>
<div style="padding-top: 50px" id="preparePayment" class="row">
    <div id="prepareCheckout">
        @Html.Partial("_PrepareCheckout", new PrepareCheckoutInput())
    </div>
</div>

<div id="payment" style="display: none">
    <div id="prePaymentInfo">

    </div>
    <div style="padding-top: 10px" id="paymentFormDiv">
        <form action="http://localhost:5180/TrustPay/TrustPayRedirect" class="paymentWidgets" data-brands="VISA MASTER AMEX"></form>
    <!--<form action="http://testappayment.azurewebsites.net/TrustPay/TrustPayRedirect" class="paymentWidgets" data-brands="VISA MASTER AMEX"></form>-->
        <p style="text-align: center">
            Trust pay test - visa - 4200000000000000, CVV - any 3 digits, Expiry Date - any date after today
        </p>
    </div>
</div>
<input type="hidden" id="checkoutId" />

<script type="text/javascript">
    $(function () {
        $('#prepareCheckout').on('submit', '#prepareCheckoutForm', function () {
            event.preventDefault();
            var $form = $('form', '#prepareCheckout');

            var params = $form.serialize();
            var postUrl = $form.attr('action');

            $.post(postUrl, params).done(function (data, textStatus, xhr) {
                var script = document.createElement("script");
                script.src = data.ReturnValue.ScriptSrc;
                script.type = "text/javascript";
                document.getElementsByTagName("head")[0].appendChild(script);
                $('#checkoutId').val(data.ReturnValue.CheckoutId);

                var args = {
                    Amount: $("#Amount").val(),
                    Currency: $("#Currency").val()
                }
                $.get('@Url.Action("GetPrePaymentInfo")', args).done(function (html) {
                    $("#prePaymentInfo").html(html);
                });

                $("#payment").show();
                $("#preparePayment").hide();

                var params = {
                CheckoutId: $('#checkoutId').val(),
                Currency: $("#Currency").val(),
                Amount: $("#Amount").val(),
                UserAccountId : null
                };
                @*$.post('@Url.Action("CreateNewPayment", "api/TrustPayApi")', params).done(function (data, textStatus, xhr) {
                });*@
            });
        });

        $('#prePaymentInfo').on('click', '#changePayment', function () {
            $("#preparePayment").show();
            $("#payment").hide();
        });
     });
</script>

WithoutDbVerison/BaseApp.Web/Views/TrustPay/TrustPayRedirect.cshtml
@model AlphaPointPayment.Web.Models.TrustPay.TrustPayRedirectInput
@{
    ViewBag.Title = "Payment Result";
}

@Html.HiddenFor(m => m.id)
@Html.HiddenFor(m => m.resourcePath)

<a href="@Url.Action("Index", "TrustPay")">Pay again</a>

<div style="text-align: center;">
    <div style="width: 500px; margin: 0 auto;">
        <div>
            <h4>
                <label id="message"> </label>
            </h4>
        </div>
        <div style="color: red">
            <h4>
                <label id="errorMessage"> </label>
            </h4>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        var args = {
            resourcePath : $('#resourcePath').val(),
			checkoutId : $('#id').val()
        };
        $.get('@Url.Action("CheckTrustPayPayment", "api/TrustPayApi")', args)
            .done(function (data) {
                if (data.ErrorMessage) {
                    $("#errorMessage").html(data.ErrorMessage);
                } else {
                    $("#message").html(data.ReturnValue.Message);
                }
            });
    });
</script>

WithoutDbVerison/BaseApp.Web/Views/TrustPay/_PrePaymentInfo.cshtml
@using BaseApp.Common;
@model AlphaPointPayment.Web.Models.TrustPay.PrePaymentInfoViewModel
@{
    Layout = null;
}

<div class="text-center">
    <h4>Payment sum @Model.Amount @Model.Currency.ToDescription()s </h4> <input class="btn btn-default" type="button" id="changePayment" value="change" />
</div>

WithoutDbVerison/BaseApp.Web/Views/TrustPay/_PrepareCheckout.cshtml
@using BaseApp.Common;
@model AlphaPointPayment.Web.Models.Api.TrustPay.PrepareCheckoutInput
@{
    Layout = null;
}

<div style="text-align: center;">
    <div style="width: 280px; margin: 0 auto;">
        @using (Html.BeginForm("PrepareCheckout", "api/TrustPayApi", null, FormMethod.Post, new { role = "form", @class = "form", id = "prepareCheckoutForm" }))
        {
            <div class="form-group">
                @Html.LabelFor(m => m.Amount, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Amount, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Amount)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Currency, new { @class = "control-label" })
                @Html.DropDownListFor(m => m.Currency, new List<SelectListItem>()
                {
                    new SelectListItem { Value = ((int)Enums.Currencies.USD).ToString(), Text = Enums.Currencies.USD.ToDescription() },
                    new SelectListItem { Value = ((int)Enums.Currencies.CAD).ToString(), Text = Enums.Currencies.CAD.ToDescription() },
                    new SelectListItem { Value = ((int)Enums.Currencies.EUR).ToString(), Text = Enums.Currencies.EUR.ToDescription() }
                }, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Currency)
            </div>           
            <div class="form-group">
                <input type="submit" value="Prepare payment" class="btn btn-success" />
            </div>
        }
    </div>
</div>