BaseApp.Web/Areas/HelpPage/Controllers/TestController.cs
using System;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using System.Web.Mvc;
using BaseApp.Web.Areas.HelpPage.Code;
using MultipartDataMediaFormatter.Infrastructure;

namespace BaseApp.Web.Areas.HelpPage.Controllers
{
    public class TestController : Controller
    {
        public TestController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public TestController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult ApiTest(string apiId)
        {
            if (String.IsNullOrEmpty(apiId))
            {
                throw new ArgumentNullException("apiId", "Not specified");
            }
            Collection<ApiDescription> apiDescriptions = Configuration.Services.GetApiExplorer().ApiDescriptions;
            ApiDescription apiDescription = apiDescriptions.FirstOrDefault(api => String.Equals(api.GetFriendlyId(), apiId, StringComparison.OrdinalIgnoreCase));

            if (apiDescription == null)
            {
                throw new Exception(string.Format("API with id {0} not found", apiId));
            }
            object model = null;

            if (apiDescription.ParameterDescriptions.Count > 1)
                throw new Exception("API test available only for 0 or 1 action parameters");

            var apiUnavail = apiDescription.ActionDescriptor.GetCustomAttributes<ApiUnavailableTestAttribute>().FirstOrDefault();
            if (apiUnavail != null)
            {
                return View("NoTestMethod");
            }

            var apiCustom = apiDescription.ActionDescriptor.GetCustomAttributes<ApiCustomTestAttribute>().FirstOrDefault();
            if (apiCustom != null)
            {
                return RedirectToAction(apiCustom.Action, apiCustom.Controller);
            }

            bool isMultiPart = false;
            if (apiDescription.ParameterDescriptions.Count == 1)
            {
                var firstParamType = apiDescription.ParameterDescriptions[0].ParameterDescriptor.ParameterType;
                if (firstParamType == typeof(FormData))
                    throw new Exception("API test unavailable for action parameter FormData");

                if (firstParamType.GetInterface(typeof(IMultipartData).Name) != null)
                {
                    isMultiPart = true;
                }

                if (firstParamType.IsClass && firstParamType != typeof(string))
                {
                    if (firstParamType.GetConstructor(Type.EmptyTypes) == null)
                    {
                        throw new Exception("API test unavailable for action parameter without empty constructor");
                    }

                    var objectGenerator = new ObjectGeneratorEx();
                    model = objectGenerator.GenerateObject(firstParamType);
                }
                else throw new Exception("API test available only for IsClass action parameter");
            }

            var testApiModel = new TestApiModel
            {
                Action = apiDescription.ActionDescriptor.ActionName,
                Controller = apiDescription.ActionDescriptor.ControllerDescriptor.ControllerName,
                Method = GetFormMethod(apiDescription.HttpMethod),
                Model = model
            };
            if (isMultiPart)
            {
                testApiModel.EncType = "multipart/form-data";
            }
            return View(testApiModel);
        }

        private static FormMethod GetFormMethod(HttpMethod apiMethod)
        {
            FormMethod method;
            if (apiMethod == System.Net.Http.HttpMethod.Get)
            {
                method = FormMethod.Get;
            }
            else if (apiMethod == System.Net.Http.HttpMethod.Post)
            {
                method = FormMethod.Post;
            }
            else throw new Exception(String.Format((string)"Test API for method {0} not supported", (object)apiMethod));
            return method;
        }
    }
}

BaseApp.Web/Controllers/DatafeedController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.SessionState;
using BaseApp.Web.Code.Infrastructure.BaseControllers;
using BaseApp.Web.Models.Datafeed;

namespace BaseApp.Web.Controllers
{
    [SessionState(SessionStateBehavior.Disabled)]
    public class DatafeedController : ControllerBaseNoAuthorize
    {
        [HttpPost]
        public ActionResult GetUsers(string prefixText, int count, string contextKey)
        {
            return AutocompleteResult(UnitOfWork.Users.GetUsersByFilter(prefixText, count).ConvertAll(m => "m.FullName").ToArray());
        }

        /// <summary>
        /// return Label: "[No matches found]" if input is empty
        /// </summary>
        private ActionResult AutocompleteResult(string[] input)
        {
            var res = new List<AutocompleteItemModel>();

            if (input == null || input.Length < 1)
            {
                res.Add(new AutocompleteItemModel() {Label = "[No matches found]"});
            }
            else
            {
                res.AddRange(input.Select(m => new AutocompleteItemModel() { Label = m, Value = m }));
            }
            return Json(res);
        }
    }
}

BaseApp.Web/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.WebPages;
using BaseApp.Data.DataContext;
using BaseApp.Web.Code.Filters;
using BaseApp.Web.Code.Infrastructure;
using BaseApp.Web.Code.Infrastructure.BaseControllers;

namespace BaseApp.Web.Controllers
{
    public class TestController : ControllerBaseNoAuthorize
    {
        [AllowAnonymous]
        public ActionResult Index()
        {
            //var c = UnitOfWork.Countries.GetCountries2().Select(m => m.Name);

            //return Json(c, JsonRequestBehavior.AllowGet);

            ClientMessage.AddError("TEST ERROR REQUEST");
            ClientMessage.AddSuccess("<p style='color:red;'>TEST SUCCESS REQUEST</p>");
           

            return View();
        }

        [HttpPost]
        public ActionResult Index(int? Country, int? State)
        {
            return View();
        }

        [Authorize]
        public ActionResult TestAjaxRedirect()
        {
            return RedirectToAction("Index", "Home");
        }

        /*public ActionResult TestError()
        {
            var user = UnitOfWork.Users.GetAll().First();
            //UnitOfWork.Users.MarkForDelete(user);
            user.Login = "test sadasd adad affffffffffffffffffffffffffffffff test sadasd adad affffffffffffffffffffffffffffffff test sadasd adad affffffffffffffffffffffffffffffff";

            try
            {
                UnitOfWork.SaveChanges();
            }
            catch (DbUpdateExceptionWrapper ex)
            {
                throw;
            }

            throw new Exception("test");
        }*/

        public void TestAjaxMesssages()
        {
            ClientMessage.AddSuccess("<p style='color: green;'>GREEN TEST SUCCESS</p>");
            ClientMessage.AddError("<p style='color: red;'>RED TEST SUCCESS</p>");
            ClientMessage.AddJavaScript("alert(111);");
        }

        public ActionResult TestMsg()
        {
            ClientMessage.AddSuccess("TEST SUCCESS REQUEST");
            return RedirectToAction("Index");
        }

        public void TestPart()
        {
            var resp = this.Response;

            resp.BufferOutput = false;
            resp.Buffer = false;

            resp.Write("1");
            resp.Flush();
            System.Threading.Thread.Sleep(3000);

            resp.Write("2");
            resp.Flush();
            System.Threading.Thread.Sleep(3000);

            resp.Write("3");
            resp.Flush();
            System.Threading.Thread.Sleep(3000);

        }

        /*public ActionResult TestTransaction()
        {
            var newUser = new User()
                          {
                              Login = "TEST",
                              Email = "TEST@test.com",
                              FirstName = "TEST",
                              LastName = "TEST",
                              Password = "1",
                              CreatedDate = DateTime.Now,
                              UpdatedDate = DateTime.Now
                          };

            UnitOfWork.Users.MarkForInsert(newUser);

            using (var tran = UnitOfWork.BeginTransaction())
            {
                UnitOfWork.SaveChanges();

                var userId = newUser.Id;

                try
                {
                    using (var innerTran = UnitOfWork.BeginTransaction())
                    {
                        newUser.FirstName = "edited";

                        UnitOfWork.SaveChanges();

                        //throw new Exception("TEST");

                        innerTran.Commit();
                    }
                }
                catch (Exception)
                {
                    
                }
                

                tran.Commit();
            }

            var users = UnitOfWork.Users.GetAll();

            return Content("OK");
        }*/
    }
}

BaseApp.Web/Views/Test/Index.cshtml
@{
    ViewBag.Title = "Test";
}

<h2>Test</h2>

<b>Autocomplete test</b>
<input type="text" data-autocomplete-url="@Url.Action("GetUsers", "Datafeed")" />
<hr/>
<input type="button" value="Test ajax redirect" onclick="testAjaxRedirect();" />
<div id="res">no data</div>

<h3>Combobox bind example (with after post restore comboboxes select items - without using ViewBag)</h3>
@using(Html.BeginForm())
{
    <div>
        <p>
            @*Countries: @Html.DropDownList("Country", DataItems.Countries)*@
        </p>
        <p>
            States: @Html.DropDownList("State", DataItems.StatesOfUSA, "-Select-")
        </p>
    </div>
    <div>
        <input type="submit" value="submit" />
    </div>
}

<div style="padding-top: 10px;">
    <p>Date: <input type="text" id="datepicker" size="30"></p>
</div>

<h3>Test ajax client messages</h3>
<a href="javascript:testAjaxMessages();">Test messages</a>

<div>
    <input type="button" value="ALERT" onclick="testAlert()" />
    &nbsp;
    <input type="button" value="CONFIRM" onclick="testConfirm()" />
    &nbsp;
    <input type="button" value="DIALOG" onclick="testDialog()" />
</div>

<script type="text/javascript">

    function testAlert() {
        SiteDialog.alert('alert show', function() { alert('alert closed'); });
    }

    function testConfirm() {
        SiteDialog.confirm('confirm show', function(isConfirmed) { alert('confirm result: ' + isConfirmed); });
    }

    function testDialog() {
        var dialog = SiteDialog.show({
            body: 'test message',
            title: 'test',
            close: function () { alert('closed'); },
            buttons: [
                {
                    text: 'Yes',
                    click: function () { alert('Yes'); }
                },
                {
                    text: 'No',
                    click: function () { alert('No'); }
                },
                {
                    text: 'Cancel',
                    click: function () {
                        dialog.close(); alert('Cancel');
                    }
                }
            ]
        });
    }

    function testAjaxRedirect() {
        $("#res").load('@Url.Action("TestAjaxRedirect", "Test")');
    }
    function testAjaxMessages() {

        $.ajax({
            method: "POST",
            url: '@Url.Content("~/api/TestApi/SaveTest")',
            contentType: "application/json",
            data: $.toJSON({ FirstString: "TEST string" }),
            success: function() {
                alert('success');
            }
        });

        $.ajax({
            cache: false,
            url: '@Url.Action("TestAjaxMesssages")'
        });
    }

    $(function () {
        $("#datepicker").datepicker();       
    });
</script>