BaseApp.Web/Areas/Admin/Controllers/UserController.cs
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading;
using System.Web.Mvc;
using BaseApp.Data.DataContext.Entities;
using BaseApp.Web.Areas.Admin.Models;
using BaseApp.Web.Code.Extensions;
using BaseApp.Web.Code.Infrastructure.BaseControllers;
using AutoMapper;

namespace BaseApp.Web.Areas.Admin.Controllers
{
    public class UserController : ControllerBaseAdminRequired
    {
        public ActionResult Index()
        {
            return View(GetUserList());
        }

        public ActionResult Edit(int id)
        {
            var user = UnitOfWork.Users.GetOrNull(id);
            if (user == null)
                return NotFoundAction();

            UserEditModel model = Mapper.Map<UserEditModel>(user);

            model.Roles = Mapper.Map<List<UserRoleModel>>(UnitOfWork.Users.GetAllRoles());
            model.Roles.ForEach(m => m.Checked = user.Roles.Any(r => r.Id == m.Id));

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(UserEditModel model)
        {
            if(ModelState.IsValid)
            {
                var user = UnitOfWork.Users.Get(model.Id);

                user = Mapper.Map(model, user);
                user.UpdatedByUserId = User.GetUserInfo().UserID;
                user.UpdatedDate = DateTime.Now;

                user.Roles.Clear();

                List<Role> allRoles = UnitOfWork.Users.GetAllRoles();
                foreach (var role in model.Roles.Where(m => m.Checked))
                {
                    user.Roles.Add(allRoles.Single(m => m.Id == role.Id));                                
                }

                UnitOfWork.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            User user = UnitOfWork.Users.Get(id);
            user.DeletedDate = DateTime.Now;
            user.DeletedByUserId = User.GetUserInfo().UserID;

            UnitOfWork.SaveChanges();

            if(Request.IsAjaxRequest())
            {
                return PartialView("_UserList", GetUserList());
            }
            return RedirectToAction("Index");
        }

        //TODO: PLEASE REMOVE THIS METHOD (ONLY FOR TRANSACTION EXAMPLE USED)
        [HttpPost]
        public ActionResult RestoreDeletedUsers()
        {
            Thread.Sleep(3000);

            List<User> users = UnitOfWork.Users.GetDeleted();

            using (var transaction = UnitOfWork.BeginTransaction())
            {
                foreach (var user in users)
                {
                    user.DeletedDate = null;
                    user.DeletedByUserId = null;
                    UnitOfWork.SaveChanges();
                }

                transaction.Commit();
            }

            if (Request.IsAjaxRequest())
            {
                return PartialView("_UserList", GetUserList());
            }
            return RedirectToAction("Index");   
        }

        private List<UserListItemModel> GetUserList()
        {
            List<User> users = UnitOfWork.Users.GetAll();
            return Mapper.Map<List<UserListItemModel>>(users);
        }
    }
}

BaseApp.Web/Areas/Admin/Views/User/Edit.cshtml
@model BaseApp.Web.Areas.Admin.Models.UserEditModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserEditModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            
                @for (int i = 0; i < Model.Roles.Count; i++)
                {
                    <div class="col-sm-offset-2 col-sm-9">
                        <input type="hidden" name="Roles[@i].Id" value="@Model.Roles[i].Id" />
                        <input type="hidden" name="Roles[@i].Name" value="@Model.Roles[i].Name" />
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="Roles[@i].Checked" id="Roles[@i].Checked" value="True"
                                       @if (Model.Roles[i].Checked) {  @: checked="checked"
                                                                   } />
                                @Model.Roles[i].Name
                            </label>
                        </div>
                    </div>
                }
                @Html.ValidationMessageFor(model => model.Roles)
            </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BaseApp.Web/Areas/Admin/Views/User/Index.cshtml
@model IEnumerable<BaseApp.Web.Areas.Admin.Models.UserListItemModel>

@{
    ViewBag.Title = "Users";
}
<h2>Users</h2>
@Html.Partial("_UserList", Model)

BaseApp.Web/Areas/Admin/Views/User/_UserList.cshtml
@using BaseApp.Data.Infrastructure
@model IEnumerable<BaseApp.Web.Areas.Admin.Models.UserListItemModel>
<div id="dvUserList">
    <div style="padding:  10px 10;">
        @Ajax.ActionLink("Restore deleted users (TEST transaction - remove in real app)", "RestoreDeletedUsers", new AjaxOptions() { HttpMethod = "POST", Confirm = "Are you sure?", UpdateTargetId = "dvUserList", LoadingElementId = "restoreLoading" })
        <span id="restoreLoading" style="color:gray; display:none; font-size:small; padding-left: 5px;">Loading...</span>
    </div>

    <table class=" table table-striped">
        <thead>
            <tr>
                <th>
                    Login
                </th>
                <th>
                    First Name
                </th>
                <th>
                    Last Name
                </th>
                <th>
                    Email
                </th>
                <th>
                    Roles
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Login)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Roles)
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "User", new { id = item.Id })">Edit</a>
                        @if (User.GetUserInfo().UserID != item.Id)
                        {
                            @:|
                            @Ajax.ActionLink("Delete", "Delete", new { id = item.Id }, new AjaxOptions() { HttpMethod = "POST", Confirm = "Are you sure?", UpdateTargetId = "dvUserList" })
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>