WithoutDbVerison/BaseApp.Web/Models/Razorpay/RazorpayInitModel.cs
using System.ComponentModel.DataAnnotations;

namespace AlphaPointPayment.Web.Models.Razorpay
{
    public class RazorpayInitModel
    {
        public string PublicKey { get; set; }
        public string LogoUrl { get; set; }

        [Required(ErrorMessage = "Email is required")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string Email { get; set; }

        [Display(Name ="Phone number")]
        [Required(ErrorMessage = "Mobile no. is required")]
        [RegularExpression("^(?!0+$)(\\+\\d{1,3}[- ]?)?(?!0+$)\\d{10,15}$", ErrorMessage = "Please enter valid phone no.")]
        public string PhoneNumber { get; set; }

        public string Method { get; set; }

        [RegularExpression("[0-9]{0,}", ErrorMessage = "Please enter valid amount")]
        [Required(ErrorMessage = "Amount is required")]
        [Display(Name = "Amount(INR paise)")]
        public decimal Amount { get; set; }
    }
}

WithoutDbVerison/BaseApp.Web/Models/Razorpay/RazorpayResponse.cs
using System.ComponentModel.DataAnnotations;

namespace AlphaPointPayment.Web.Models.Razorpay
{
    public class RazorpayResponse
    {
        public string razorpay_payment_id { get; set; }
    }
}

WithoutDbVerison/BaseApp.Web/Controllers/RazorpayController.cs
using AlphaPointPayment.Web.Models.Razorpay;
using BaseApp.Common;
using BaseApp.Web.Code.Infrastructure.BaseControllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AlphaPointPayment.Web.Controllers
{
    /// <summary>
    /// Controller for demonstration
    /// </summary>
    public class RazorpayController : ControllerBaseNoAuthorize
    {

        // GET: Razorpay
        public ActionResult Index()
        {
            return View(new RazorpayInitModel());
        }

        /// <summary>
        /// Prepared data to razor pay checkout
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        public ActionResult PrepareCheckout(RazorpayInitModel input)
        {
            input.PublicKey = ConfigSettings.RazorPayKey_id;
            input.LogoUrl = "https://alphapoint.com/assets/img/default_logo.svg";
            input.Method = "card";

            return View(input);
        }
    }
}

WithoutDbVerison/BaseApp.Web/Views/Razorpay/Index.cshtml
@model AlphaPointPayment.Web.Models.Razorpay.RazorpayInitModel

@{
    ViewBag.Title = "Razorpay payment";
}


@using (Html.BeginForm("PrepareCheckout", "Razorpay", null, FormMethod.Post, new { role = "form", @class = "form", id = "prepareCheckoutForm" }))
{
    @Html.AntiForgeryToken()
    <h3 style="text-align:center;">Please enter amount and your contact data for confirm payment.</h3>
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-2">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-5">
                <input type="submit" value="Pay with Razorpay" class="btn btn-default" />
            </div>
        </div>
    </div>
}

WithoutDbVerison/BaseApp.Web/Views/Razorpay/PrepareCheckout.cshtml
@model AlphaPointPayment.Web.Models.Razorpay.RazorpayInitModel

@{
    ViewBag.Title = "Prepare checkout";
}

<style>
    .razorpay-payment-button{
        background-color: #4CAF50; /* Green */
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
    }
</style>

<div>
    @{ var castAmount = Model.Amount / 100;}
    <h3>You will apply your balance to @castAmount INR</h3>
    <form action="http://localhost:5180/api/RazorpayApi/CapturePayment" method="POST">
        <!-- Note that the amount is in paise: 5000 => 50 INR -->
        <script src="https://checkout.razorpay.com/v1/checkout.js"
                data-key=@Html.Raw(Json.Encode(Model.PublicKey))
                data-buttontext="Apply"
                data-name="AlphaPoint"
                data-description="AlphaPoint payment"
                data-image=@Html.Raw(Json.Encode(Model.LogoUrl))
                data-theme.color="#F37254"
                data-prefill.email =@Html.Raw(Json.Encode(Model.Email))
                data-prefill.contact =@Html.Raw(Json.Encode(Model.PhoneNumber))
                data-prefill.method =@Html.Raw(Json.Encode(Model.Method))
                data-amount =@Html.Raw(Json.Encode(Model.Amount))>
        </script>
    </form>
</div>